<a href="https://colab.research.google.com/github/Muniz97/Yellow-fever-Febre-Amarela/blob/main/Yellow_Fever.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Yellow Fever Brazil 1994-2021

In [36]:
'''
Conhecendo os dados
'''

'\nConhecendo os dados\n'

In [37]:
import pandas as pd
import numpy as np

In [50]:
url = 'https://raw.githubusercontent.com/Muniz97/Yellow-fever-Febre-Amarela/main/fa_casoshumanos_1994-2021.csv'
#url = '/content/fa_casoshumanos_1994-2021.csv'

In [51]:
dados_raw = pd.read_csv(url, sep = ';', encoding="ISO-8859-1")

In [52]:
dados_raw.head(25)

,ID,MACRORREG_LPI,COD_UF_LPI,UF_LPI,COD_MUN_LPI,MUN_LPI,SEXO,IDADE,DT_IS,SE_IS,MES_IS,ANO_IS,MONITORAMENTO_IS,OBITO
0,1,N,14,RR,140005.0,Alto Alegre,M,NaN,29/11/1994,48.0,11.0,1994,1994/1995,SIM
1,2,N,14,RR,140045.0,Pacaraima,M,19,19/02/1995,8.0,2.0,1995,1994/1995,NÃO
2,3,NE,21,MA,210060.0,Amarante do Maranhão,M,32,01/04/1995,13.0,4.0,1995,1994/1995,IGN
3,4,NE,21,MA,210060.0,Amarante do Maranhão,M,33,03/04/1995,14.0,4.0,1995,1994/1995,SIM
4,5,N,15,PA,150270.0,Conceição do Araguaia,M,26,12/04/1995,15.0,4.0,1995,1994/1995,SIM
5,6,N,13,AM,130410.0,Tapauá,M,29,26/01/1996,4.0,1.0,1996,1995/1996,SIM
6,7,N,13,AM,130356.0,Rio Preto da Eva,M,38,27/01/1996,4.0,1.0,1996,1995/1996,SIM
7,8,N,13,AM,130255.0,Manaquiri,M,46,30/01/1996,5.0,1.0,1996,1995/1996,SIM
8,9,N,13,AM,130250.0,Manacapuru,M,20,11/02/1996,7.0,2.0,1996,1995/1996,SIM
9,10,N,13,AM,130360.0,Santa Isabel do Rio Negro,M,27,NaN,NaN,NaN,1996,1995/1996,SIM
10,11,N,13,AM,130110.0,Careiro,F,23,13/03/1996,11.0,3.0,1996,1995/1996,SIM
11,12,N,13,AM,130010.0,Anori,M,14,14/03/1996,11.0,3.0,1996,1995/1996,SIM
12,13,N,13,AM,130255.0,Manaquiri,M,26,16/03/1996,11.0,3.0,1996,1995/1996,SIM
13,14,N,13,AM,130185.0,Iranduba,F,23,17/03/1996,12.0,3.0,1996,1995/1996,SIM
14,15,N,13,AM,130406.0,Tabatinga,M,21,01/04/1996,14.0,4.0,1996,1995/1996,NÃO
15,16,N,13,AM,130250.0,Manacapuru,M,38,30/06/1996,27.0,6.0,1996,1995/1996,SIM
16,17,N,13,AM,130040.0,Barcelos,M,20,03/08/1996,31.0,8.0,1996,1996/1997,NÃO
17,18,N,13,AM,130260.0,Manaus,M,42,09/08/1996,32.0,8.0,1996,1996/1997,SIM
18,19,CO,50,MS,500660.0,Ponta Porã,F,17,29/08/1996,35.0,8.0,1996,1996/1997,SIM
19,20,N,13,AM,130360.0,Santa Isabel do Rio Negro,F,14,05/11/1996,45.0,11.0,1996,1996/1997,SIM
20,21,N,11,RO,110020.0,Porto Velho,M,31,15/04/1997,16.0,4.0,1997,1996/1997,SIM
21,22,N,15,PA,150050.0,Almeirim,M,25,20/06/1997,25.0,6.0,1997,1996/1997,SIM
22,23,N,15,PA,150050.0,Almeirim,M,24,08/07/1997,28.0,7.0,1997,1997/1998,SIM
23,24,N,15,PA,150030.0,Afuá,M,19,03/02/1998,5.0,2.0,1998,1997/1998,SIM
24,25,N,15,PA,150030.0,Afuá,M,24,20/02/1998,7.0,2.0,1998,1997/1998,NÃO

In [53]:
dados_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2758 entries, 0 to 2757
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                2758 non-null   int64
 1   MACRORREG_LPI     2758 non-null   object
 2   COD_UF_LPI        2758 non-null   int64
 3   UF_LPI            2758 non-null   object
 4   COD_MUN_LPI       2751 non-null   float64
 5   MUN_LPI           2752 non-null   object
 6   SEXO              2757 non-null   object
 7   IDADE             2756 non-null   object
 8   DT_IS             2753 non-null   object
 9   SE_IS             2742 non-null   float64
 10  MES_IS            2747 non-null   float64
 11  ANO_IS            2758 non-null   int64
 12  MONITORAMENTO_IS  2758 non-null   object
 13  OBITO             2758 non-null   object
dtypes: float64(3), int64(3), object(8)
memory usage: 301.8+ KB

In [54]:
dados_raw.isnull().sum()

ID                   0
MACRORREG_LPI        0
COD_UF_LPI           0
UF_LPI               0
COD_MUN_LPI          7
MUN_LPI              6
SEXO                 1
IDADE                2
DT_IS                5
SE_IS               16
MES_IS              11
ANO_IS               0
MONITORAMENTO_IS     0
OBITO                0
dtype: int64

In [55]:
dados_raw = dados_raw.dropna() # Por ser poucos valores nulos os mesmo foram desconsiderados
dados_raw.head()

,ID,MACRORREG_LPI,COD_UF_LPI,UF_LPI,COD_MUN_LPI,MUN_LPI,SEXO,IDADE,DT_IS,SE_IS,MES_IS,ANO_IS,MONITORAMENTO_IS,OBITO
1,2,N,14,RR,140045.0,Pacaraima,M,19,19/02/1995,8.0,2.0,1995,1994/1995,NÃO
2,3,NE,21,MA,210060.0,Amarante do Maranhão,M,32,01/04/1995,13.0,4.0,1995,1994/1995,IGN
3,4,NE,21,MA,210060.0,Amarante do Maranhão,M,33,03/04/1995,14.0,4.0,1995,1994/1995,SIM
4,5,N,15,PA,150270.0,Conceição do Araguaia,M,26,12/04/1995,15.0,4.0,1995,1994/1995,SIM
5,6,N,13,AM,130410.0,Tapauá,M,29,26/01/1996,4.0,1.0,1996,1995/1996,SIM