Yellow Fever Brazil 1994-2021 / Febre Amarela Brasil 1994-2021

In [335]:
import pandas as pd
import numpy as np

In [336]:
url = 'https://raw.githubusercontent.com/Muniz97/Yellow-fever-Febre-Amarela/main/Datasets/fa_casoshumanos_1994-2021.csv'

In [337]:
dados_raw = pd.read_csv(url, sep = ';', encoding="ISO-8859-1")

In [338]:
# Display
pd.options.display.float_format = '{:.3f}'.format

In [339]:
dados_raw.head(100)

,ID,MACRORREG_LPI,COD_UF_LPI,UF_LPI,COD_MUN_LPI,MUN_LPI,SEXO,IDADE,DT_IS,SE_IS,MES_IS,ANO_IS,MONITORAMENTO_IS,OBITO
0,1,N,14,RR,140005.000,Alto Alegre,M,NaN,29/11/1994,48.000,11.000,1994,1994/1995,SIM
1,2,N,14,RR,140045.000,Pacaraima,M,19,19/02/1995,8.000,2.000,1995,1994/1995,NÃO
2,3,NE,21,MA,210060.000,Amarante do Maranhão,M,32,01/04/1995,13.000,4.000,1995,1994/1995,IGN
3,4,NE,21,MA,210060.000,Amarante do Maranhão,M,33,03/04/1995,14.000,4.000,1995,1994/1995,SIM
4,5,N,15,PA,150270.000,Conceição do Araguaia,M,26,12/04/1995,15.000,4.000,1995,1994/1995,SIM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,N,15,PA,150030.000,Afuá,M,16,15/05/1999,19.000,5.000,1999,1998/1999,IGN
96,97,N,15,PA,150180.000,Breves,M,11,15/05/1999,19.000,5.000,1999,1998/1999,IGN
97,98,N,15,PA,150658.000,Santa Maria das Barreiras,F,17,Assintomático,NaN,NaN,1999,1998/1999,NÃO
98,99,N,15,PA,150270.000,Conceição do Araguaia,M,15,27/05/1999,21.000,5.000,1999,1998/1999,SIM
99,100,N,13,AM,130070.000,Boca do Acre,M,31,30/05/1999,22.000,5.000,1999,1998/1999,NÃO

In [340]:
dados_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2758 entries, 0 to 2757
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                2758 non-null   int64
 1   MACRORREG_LPI     2758 non-null   object
 2   COD_UF_LPI        2758 non-null   int64
 3   UF_LPI            2758 non-null   object
 4   COD_MUN_LPI       2751 non-null   float64
 5   MUN_LPI           2752 non-null   object
 6   SEXO              2757 non-null   object
 7   IDADE             2756 non-null   object
 8   DT_IS             2753 non-null   object
 9   SE_IS             2742 non-null   float64
 10  MES_IS            2747 non-null   float64
 11  ANO_IS            2758 non-null   int64
 12  MONITORAMENTO_IS  2758 non-null   object
 13  OBITO             2758 non-null   object
dtypes: float64(3), int64(3), object(8)
memory usage: 301.8+ KB

Datas nulls and duplicates / Dados nulos e duplicados

In [341]:
dados_raw.isnull().sum()

ID                   0
MACRORREG_LPI        0
COD_UF_LPI           0
UF_LPI               0
COD_MUN_LPI          7
MUN_LPI              6
SEXO                 1
IDADE                2
DT_IS                5
SE_IS               16
MES_IS              11
ANO_IS               0
MONITORAMENTO_IS     0
OBITO                0
dtype: int64

In [342]:
dados_raw = dados_raw.dropna() # Por serem poucos dados nulos os mesmo foram removidos

In [343]:
# Verifica atual volumetria
dados_raw.count()

ID                  2734
MACRORREG_LPI       2734
COD_UF_LPI          2734
UF_LPI              2734
COD_MUN_LPI         2734
MUN_LPI             2734
SEXO                2734
IDADE               2734
DT_IS               2734
SE_IS               2734
MES_IS              2734
ANO_IS              2734
MONITORAMENTO_IS    2734
OBITO               2734
dtype: int64

In [344]:
# Verifica se existe duplicados
dados_raw.drop_duplicates().count() # No datas duplicates / Sem dados duplicados

ID                  2734
MACRORREG_LPI       2734
COD_UF_LPI          2734
UF_LPI              2734
COD_MUN_LPI         2734
MUN_LPI             2734
SEXO                2734
IDADE               2734
DT_IS               2734
SE_IS               2734
MES_IS              2734
ANO_IS              2734
MONITORAMENTO_IS    2734
OBITO               2734
dtype: int64

Convert features numerical / Convertendo features númericas

In [345]:
# Separando features númericas
list_int = ['IDADE','SE_IS','MES_IS','ANO_IS'] # COD_UF_LPI and COD_MUN_LPI are objects

In [346]:
# Convertendo
dados_raw['IDADE'] = dados_raw['IDADE'].str.replace(',', '.').astype(float)

<ipython-input-346-02bf1b946292>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_raw['IDADE'] = dados_raw['IDADE'].str.replace(',', '.').astype(float)

In [347]:
# int convert
dados_raw[list_int] = dados_raw[list_int].astype(int)

<ipython-input-347-f30e37c696b3>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_raw[list_int] = dados_raw[list_int].astype(int)

In [348]:
dados_raw.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2734 entries, 1 to 2757
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                2734 non-null   int64
 1   MACRORREG_LPI     2734 non-null   object
 2   COD_UF_LPI        2734 non-null   int64
 3   UF_LPI            2734 non-null   object
 4   COD_MUN_LPI       2734 non-null   float64
 5   MUN_LPI           2734 non-null   object
 6   SEXO              2734 non-null   object
 7   IDADE             2734 non-null   int64
 8   DT_IS             2734 non-null   object
 9   SE_IS             2734 non-null   int64
 10  MES_IS            2734 non-null   int64
 11  ANO_IS            2734 non-null   int64
 12  MONITORAMENTO_IS  2734 non-null   object
 13  OBITO             2734 non-null   object
dtypes: float64(1), int64(6), object(7)
memory usage: 320.4+ KB

Datetime / Datas

In [349]:
# Date
from datetime import datetime

In [350]:
dados_raw.head(25)

,ID,MACRORREG_LPI,COD_UF_LPI,UF_LPI,COD_MUN_LPI,MUN_LPI,SEXO,IDADE,DT_IS,SE_IS,MES_IS,ANO_IS,MONITORAMENTO_IS,OBITO
1,2,N,14,RR,140045.000,Pacaraima,M,19,19/02/1995,8,2,1995,1994/1995,NÃO
2,3,NE,21,MA,210060.000,Amarante do Maranhão,M,32,01/04/1995,13,4,1995,1994/1995,IGN
3,4,NE,21,MA,210060.000,Amarante do Maranhão,M,33,03/04/1995,14,4,1995,1994/1995,SIM
4,5,N,15,PA,150270.000,Conceição do Araguaia,M,26,12/04/1995,15,4,1995,1994/1995,SIM
5,6,N,13,AM,130410.000,Tapauá,M,29,26/01/1996,4,1,1996,1995/1996,SIM
6,7,N,13,AM,130356.000,Rio Preto da Eva,M,38,27/01/1996,4,1,1996,1995/1996,SIM
7,8,N,13,AM,130255.000,Manaquiri,M,46,30/01/1996,5,1,1996,1995/1996,SIM
8,9,N,13,AM,130250.000,Manacapuru,M,20,11/02/1996,7,2,1996,1995/1996,SIM
10,11,N,13,AM,130110.000,Careiro,F,23,13/03/1996,11,3,1996,1995/1996,SIM
11,12,N,13,AM,130010.000,Anori,M,14,14/03/1996,11,3,1996,1995/1996,SIM
12,13,N,13,AM,130255.000,Manaquiri,M,26,16/03/1996,11,3,1996,1995/1996,SIM
13,14,N,13,AM,130185.000,Iranduba,F,23,17/03/1996,12,3,1996,1995/1996,SIM
14,15,N,13,AM,130406.000,Tabatinga,M,21,01/04/1996,14,4,1996,1995/1996,NÃO
15,16,N,13,AM,130250.000,Manacapuru,M,38,30/06/1996,27,6,1996,1995/1996,SIM
16,17,N,13,AM,130040.000,Barcelos,M,20,03/08/1996,31,8,1996,1996/1997,NÃO
17,18,N,13,AM,130260.000,Manaus,M,42,09/08/1996,32,8,1996,1996/1997,SIM
18,19,CO,50,MS,500660.000,Ponta Porã,F,17,29/08/1996,35,8,1996,1996/1997,SIM
19,20,N,13,AM,130360.000,Santa Isabel do Rio Negro,F,14,05/11/1996,45,11,1996,1996/1997,SIM
20,21,N,11,RO,110020.000,Porto Velho,M,31,15/04/1997,16,4,1997,1996/1997,SIM
21,22,N,15,PA,150050.000,Almeirim,M,25,20/06/1997,25,6,1997,1996/1997,SIM
22,23,N,15,PA,150050.000,Almeirim,M,24,08/07/1997,28,7,1997,1997/1998,SIM
23,24,N,15,PA,150030.000,Afuá,M,19,03/02/1998,5,2,1998,1997/1998,SIM
24,25,N,15,PA,150030.000,Afuá,M,24,20/02/1998,7,2,1998,1997/1998,NÃO
25,26,N,15,PA,150030.000,Afuá,M,23,21/02/1998,7,2,1998,1997/1998,SIM
26,27,CO,51,MT,510558.000,Marcelândia,M,41,27/02/1998,8,2,1998,1997/1998,SIM

In [351]:
dados_raw.DT_IS

1       19/02/1995
2       01/04/1995
3       03/04/1995
4       12/04/1995
5       26/01/1996
           ...
2753    19/03/2021
2754    06/01/2021
2755    19/05/2021
2756    07/07/2021
2757    09/12/2021
Name: DT_IS, Length: 2734, dtype: object

In [352]:
dados_raw.DT_IS.unique()

array(['19/02/1995', '01/04/1995', '03/04/1995', '12/04/1995',
       '26/01/1996', '27/01/1996', '30/01/1996', '11/02/1996',
       '13/03/1996', '14/03/1996', '16/03/1996', '17/03/1996',
       '01/04/1996', '30/06/1996', '03/08/1996', '09/08/1996',
       '29/08/1996', '05/11/1996', '15/04/1997', '20/06/1997',
       '08/07/1997', '03/02/1998', '20/02/1998', '21/02/1998',
       '27/02/1998', '28/02/1998', '21/03/1998', '23/03/1998',
       '01/04/1998', '09/04/1998', '11/04/1998', '14/04/1998',
       '17/04/1998', '20/04/1998', '21/04/1998', '26/04/1998',
       '30/04/1998', '03/05/1998', '07/05/1998', '18/05/1998',
       '26/05/1998', '11/06/1998', '14/06/1998', '26/06/1998',
       '03/07/1998', '07/07/1998', '17/09/1998', '17/10/1998',
       '10/11/1998', '18/01/1999', '24/01/1999', '28/01/1999',
       '03/02/1999', '09/02/1999', '12/02/1999', '13/02/1999',
       '16/02/1999', '22/02/1999', '24/02/1999', '28/02/1999',
       '05/03/1999', '08/03/1999', '09/03/1999', '10/03/1999',
       '12/03/1999', '24/03/1999', '28/03/1999', '04/04/1999',
       '05/04/1999', '07/04/1999', '13/04/1999', '03/05/1999',
       '07/05/1999', '14/05/1999', '15/05/1999', '27/05/1999',
       '30/05/1999', '04/06/1999', '14/06/1999', '16/06/1999',
       '18/07/1999', '16/08/1999', '09/09/1999', '24/09/1999',
       '26/09/1999', '23/10/1999', '07/11/1999', '25/11/1999',
       '07/12/1999', '09/12/1999', '10/12/1999', '13/12/1999',
       '14/12/1999', '15/12/1999', '17/12/1999', '20/12/1999',
       '23/12/1999', '27/12/1999', '28/12/1999', '29/12/1999',
       '30/12/1999', '31/12/1999', '01/01/2000', '02/01/2000',
       '03/01/2000', '04/01/2000', '05/01/2000', '06/01/2000',
       '09/01/2000', '10/01/2000', '11/01/2000', '12/01/2000',
       '14/01/2000', '15/01/2000', '16/01/2000', '17/01/2000',
       '19/01/2000', '20/01/2000', '23/01/2000', '02/02/2000',
       '11/02/2000', '12/02/2000', '13/02/2000', '14/02/2000',
       '15/02/2000', '16/02/2000', '18/02/2000', '19/02/2000',
       '20/02/2000', '22/02/2000', '24/02/2000', '26/02/2000',
       '28/02/2000', '03/03/2000', '04/03/2000', '07/03/2000',
       '08/03/2000', '09/03/2000', '10/03/2000', '11/03/2000',
       '14/03/2000', '22/03/2000', '24/03/2000', '25/03/2000',
       '28/03/2000', '30/03/2000', '06/04/2000', '08/04/2000',
       '09/04/2000', '25/04/2000', '02/05/2000', '08/05/2000',
       '21/05/2000', '01/06/2000', '21/06/2000', '29/06/2000',
       '24/09/2000', '14/01/2001', '16/01/2001', '23/01/2001',
       '25/01/2001', '26/01/2001', '30/01/2001', '02/02/2001',
       '03/02/2001', '06/02/2001', '07/02/2001', '09/02/2001',
       '12/02/2001', '14/02/2001', '15/02/2001', '18/02/2001',
       '19/02/2001', '22/02/2001', '25/02/2001', '27/02/2001',
       '28/02/2001', '01/03/2001', '03/03/2001', '04/03/2001',
       '06/03/2001', '07/03/2001', '18/03/2001', '19/03/2001',
       '10/04/2001', '08/06/2001', '24/06/2001', '28/07/2001',
       '05/08/2001', '02/11/2001', '29/12/2001', '03/01/2002',
       '01/02/2002', '02/03/2002', '10/03/2002', '26/03/2002',
       '10/05/2002', '20/12/2002', '21/12/2002', '26/12/2002',
       '27/12/2002', '28/12/2002', '29/12/2002', '02/01/2003',
       '01/01/2003', '03/01/2003', '08/01/2003', '09/01/2003',
       '06/01/2003', '12/01/2003', '13/01/2003', '14/01/2003',
       '16/01/2003', '17/01/2003', '15/01/2003', '18/01/2003',
       '19/01/2003', '20/01/2003', '26/01/2003', '21/01/2003',
       '23/01/2003', '25/01/2003', '30/01/2003', '02/02/2003',
       '03/02/2003', '08/02/2003', '14/02/2003', '15/02/2003',
       '16/02/2003', '25/02/2003', '14/03/2003', '18/03/2003',
       '25/03/2003', '03/04/2003', '05/04/2003', '13/05/2003',
       '01/09/2003', '02/01/2004', '18/03/2004', '23/03/2004',
       '25/04/2004', '19/06/2004', '22/11/2004', '14/01/2005',
       '11/06/2005', '06/12/2005', '26/02/2006', '22/03/2006',
       '12/02/2007', '03/03/2007', '17/03/2007', '10/04/2007',
       '20/04/2007', '21/06/2007', '03/09/2007', '21/12/2007',
       '22/12/2007', '16/12/2007', '23/12/2007', '28/12/2007',
       '26/12/2007', '02/01/2008', '03/01/2008', '04/01/2008',
       '06/01/2008', '07/01/2008', '08/01/2008', '09/01/2008',
       '11/01/2008', '12/01/2008', '13/01/2008', '14/01/2008',
       '15/01/2008', '17/01/2008', '18/01/2008', '19/01/2008',
       '21/01/2008', '25/01/2008', '28/01/2008', '01/02/2008',
       '14/02/2008', '10/02/2008', '26/02/2008', '24/02/2008',
       '25/02/2008', '18/04/2008', '22/04/2008', '23/05/2008',
       '01/06/2008', '12/06/2008', '10/12/2008', '18/12/2008',
       '28/12/2008', '30/12/2008', '31/12/2008', '01/01/2009',
       '02/01/2009', '12/01/2009', '14/01/2009', '22/02/2009',
       '23/02/2009', '27/02/2009', '06/03/2009', '07/03/2009',
       '08/03/2009', '09/03/2009', '10/03/2009', '11/03/2009',
       '12/03/2009', '14/03/2009', '15/03/2009', '16/03/2009',
       '17/03/2009', '19/03/2009', '20/03/2009', '21/03/2009',
       '22/03/2009', '23/03/2009', '25/03/2009', '26/03/2009',
       '27/03/2009', '01/04/2009', '25/04/2009', '18/05/2009',
       '24/08/2009', '18/09/2009', '05/01/2009', '17/02/2010',
       '13/06/2010', '15/01/2011', '08/05/2011', '07/01/2013',
       '18/03/2013', '20/08/2013', '11/05/2014', '28/01/2015',
       '30/01/2015', '18/02/2015', '23/03/2015', '06/05/2015',
       '14/05/2015', '26/07/2015', '22/12/2015', '21/03/2016',
       '18/03/2016', '18/05/2016', '09/04/2016', '04/01/2016',
       '15/07/2016', '18/12/2016', '04/01/2017', '28/12/2016',
       '29/12/2016', '31/12/2016', '23/12/2016', '26/12/2016',
       '25/12/2016', '24/12/2016', '08/01/2017', '19/12/2016',
       '02/01/2017', '05/01/2017', '07/01/2017', '01/01/2017',
       '12/12/2016', '09/01/2017', '06/01/2017', '10/01/2017',
       '11/01/2017', '03/01/2017', '13/01/2017', '30/12/2016',
       '14/01/2017', '19/01/2017', '21/01/2017', '26/01/2017',
       '15/01/2017', '18/01/2017', '12/01/2017', '20/01/2017',
       '31/01/2017', '29/01/2017', '01/02/2017', '04/02/2017',
       '22/02/2017', '01/03/2017', '18/02/2017', '25/02/2017',
       '05/02/2017', '15/03/2017', '16/03/2017', '14/03/2017',
       '07/03/2017', '22/01/2017', '13/03/2017', '11/03/2017',
       '27/03/2017', '28/03/2017', '21/12/2016', '17/02/2017',
       '19/03/2017', '23/03/2017', '24/01/2017', '24/03/2017',
       '26/03/2017', '31/03/2017', '17/01/2017', '04/04/2017',
       '07/04/2017', '23/01/2017', '30/03/2017', '01/04/2017',
       '02/04/2017', '25/01/2017', '03/04/2017', '06/04/2017',
       '27/01/2017', '09/04/2017', '11/04/2017', '14/04/2017',
       '16/04/2017', '17/04/2017', '18/04/2017', '19/04/2017',
       '20/04/2017', '21/04/2017', '26/04/2017', '27/04/2017',
       '28/01/2017', '30/01/2017', '16/01/2017', '10/05/2017',
       '22/12/2016', '20/12/2016', '14/02/2017', '24/02/2017',
       '02/03/2017', '10/04/2017', '06/02/2017', '02/02/2017',
       '07/02/2017', '09/02/2017', '23/02/2017', '15/02/2017',
       '20/02/2017', '12/02/2017', '13/02/2017', '27/02/2017',
       '28/02/2017', '09/03/2017', '11/02/2017', '10/02/2017',
       '10/03/2017', '19/02/2017', '06/03/2017', '08/02/2017',
       '16/02/2017', '04/03/2017', '29/03/2017', '08/03/2017',
       '03/03/2017', '12/03/2017', '20/03/2017', '21/03/2017',
       '21/02/2017', '26/02/2017', '17/03/2017', '18/03/2017',
       '22/03/2017', '25/03/2017', '03/02/2017', '05/04/2017',
       '12/04/2017', '15/04/2017', '24/04/2017', '30/04/2017',
       '09/05/2017', '22/04/2017', '12/05/2017', '29/04/2017',
       '16/06/2017', '09/06/2017', '26/05/2017', '22/05/2017',
       '01/06/2017', '06/05/2017', '02/10/2017', '08/07/2017',
       '09/07/2017', '23/09/2017', '23/11/2017', '29/08/2017',
       '05/11/2017', '11/11/2017', '23/12/2017', '13/12/2017',
       '24/12/2017', '25/12/2017', '27/12/2017', '26/12/2017',
       '29/12/2017', '09/12/2017', '21/12/2017', '28/12/2017',
       '30/12/2017', '02/01/2018', '31/12/2017', '08/12/2017',
       '22/12/2017', '17/12/2017', '01/01/2018', '04/01/2018',
       '06/01/2018', '03/01/2018', '10/01/2018', '19/12/2017',
       '05/01/2018', '08/01/2018', '07/01/2018', '11/01/2018',
       '09/01/2018', '12/01/2018', '13/01/2018', '14/01/2018',
       '15/01/2018', '20/12/2017', '05/12/2017', '15/12/2017',
       '16/01/2018', '17/01/2018', '22/01/2018', '20/01/2018',
       '19/01/2018', '18/01/2018', '31/01/2018', '21/01/2018',
       '23/01/2018', '28/01/2018', '26/01/2018', '25/01/2018',
       '24/01/2018', '27/01/2018', '29/01/2018', '30/01/2018',
       '01/02/2018', '04/02/2018', '02/02/2018', '03/02/2018',
       '05/02/2018', '06/02/2018', '12/02/2018', '10/02/2018',
       '11/02/2018', '09/02/2018', '07/02/2018', '08/02/2018',
       '14/02/2018', '13/02/2018', '15/02/2018', '16/02/2018',
       '18/02/2018', '17/02/2018', '20/02/2018', '19/02/2018',
       '21/02/2018', '24/02/2018', '26/02/2018', '22/02/2018',
       '23/02/2018', '25/02/2018', '27/02/2018', '01/03/2018',
       '28/02/2018', '04/03/2018', '02/03/2018', '06/03/2018',
       '03/03/2018', '05/03/2018', '07/03/2018', '09/03/2018',
       '10/03/2018', '14/03/2018', '12/03/2018', '15/03/2018',
       '08/03/2018', '13/03/2018', '11/03/2018', '19/03/2018',
       '22/03/2018', '16/03/2018', '18/03/2018', '23/03/2018',
       '20/03/2018', '28/03/2018', '24/03/2018', '04/04/2018',
       '02/04/2018', '26/03/2018', '30/03/2018', '06/04/2018',
       '01/04/2018', '05/04/2018', '27/03/2018', '25/03/2018',
       '11/04/2018', '29/03/2018', '17/03/2018', '21/03/2018',
       '13/04/2018', '14/04/2018', '12/04/2018', '10/04/2018',
       '07/04/2018', '16/04/2018', '31/03/2018', '09/04/2018',
       '17/04/2018', '03/04/2018', '08/04/2018', '18/04/2018',
       '19/04/2018', '22/04/2018', '24/04/2018', '30/04/2018',
       '25/04/2018', '28/04/2018', '26/04/2018', '02/05/2018',
       '06/06/2018', '03/05/2018', '01/05/2018', '07/05/2018',
       '15/04/2018', '08/05/2018', '04/05/2018', '29/04/2018',
       '20/10/2018', '11/12/2018', '03/01/2019', '21/12/2018',
       '31/12/2018', '04/01/2019', '26/12/2018', '06/01/2019',
       '07/01/2019', '08/01/2019', '12/01/2019', '01/01/2019',
       '10/01/2019', '13/01/2019', '14/01/2019', '15/01/2019',
       '24/01/2019', '22/01/2019', '18/01/2019', '16/01/2019',
       '21/01/2019', '23/01/2019', '27/01/2019', '26/01/2019',
       '01/02/2019', '28/01/2019', '31/01/2019', '30/01/2019',
       '29/01/2019', '05/02/2019', '03/02/2019', '14/02/2019',
       '13/02/2019', '10/02/2019', '18/02/2019', '17/02/2019',
       '20/02/2019', '19/02/2019', '27/02/2019', '09/03/2019',
       '03/03/2019', '07/03/2019', '25/02/2019', '06/03/2019',
       '12/03/2019', '02/02/2019', '23/02/2019', '10/03/2019',
       '04/03/2019', '21/03/2019', '11/03/2019', '03/05/2019',
       '27/04/2019', '25/04/2019', '02/12/2018', '06/02/2019',
       '22/02/2019', '25/03/2019', '23/06/2019', '28/02/2019',
       '02/07/2019', '16/01/2020', '24/01/2020', '05/02/2020',
       '13/02/2020', '18/02/2020', '22/02/2020', '30/01/2020',
       '31/01/2020', '26/02/2020', '11/03/2020', '20/03/2020',
       '07/03/2020', '04/03/2020', '03/04/2020', '08/04/2020',
       '10/04/2020', '15/04/2020', '02/05/2020', '17/05/2021',
       '29/03/2021', '26/02/2021', '21/04/2021', '20/03/2021',
       '22/04/2021', '19/03/2021', '06/01/2021', '19/05/2021',
       '07/07/2021', '09/12/2021'], dtype=object)

In [353]:
dados_raw['DT_IS'] = dados_raw['DT_IS'].apply(lambda x: datetime.strptime(x, "%d/%m/%Y")) # Valores fora do formato data foram removidos / brazilian date format

In [354]:
dados_raw['DIA_IS'] = dados_raw['DT_IS'].dt.day # 'DIA' is day

String

In [355]:
list_string = ['MACRORREG_LPI', 'UF_LPI', 'MUN_LPI', 'SEXO', 'MONITORAMENTO_IS' ,'OBITO'] # features are strings

In [356]:
dados_raw[list_string] = dados_raw[list_string].applymap(lambda x: x.upper()) # applymap serve para quando se tem mais de um variavel

In [357]:
dados_raw.head()

,ID,MACRORREG_LPI,COD_UF_LPI,UF_LPI,COD_MUN_LPI,MUN_LPI,SEXO,IDADE,DT_IS,SE_IS,MES_IS,ANO_IS,MONITORAMENTO_IS,OBITO,DIA_IS
1,2,N,14,RR,140045.000,PACARAIMA,M,19,1995-02-19,8,2,1995,1994/1995,NÃO,19
2,3,NE,21,MA,210060.000,AMARANTE DO MARANHÃO,M,32,1995-04-01,13,4,1995,1994/1995,IGN,1
3,4,NE,21,MA,210060.000,AMARANTE DO MARANHÃO,M,33,1995-04-03,14,4,1995,1994/1995,SIM,3
4,5,N,15,PA,150270.000,CONCEIÇÃO DO ARAGUAIA,M,26,1995-04-12,15,4,1995,1994/1995,SIM,12
5,6,N,13,AM,130410.000,TAPAUÁ,M,29,1996-01-26,4,1,1996,1995/1996,SIM,26

In [358]:
dados_raw.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2734 entries, 1 to 2757
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                2734 non-null   int64
 1   MACRORREG_LPI     2734 non-null   object
 2   COD_UF_LPI        2734 non-null   int64
 3   UF_LPI            2734 non-null   object
 4   COD_MUN_LPI       2734 non-null   float64
 5   MUN_LPI           2734 non-null   object
 6   SEXO              2734 non-null   object
 7   IDADE             2734 non-null   int64
 8   DT_IS             2734 non-null   datetime64[ns]
 9   SE_IS             2734 non-null   int64
 10  MES_IS            2734 non-null   int64
 11  ANO_IS            2734 non-null   int64
 12  MONITORAMENTO_IS  2734 non-null   object
 13  OBITO             2734 non-null   object
 14  DIA_IS            2734 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(7), object(6)
memory usage: 341.8+ KB

In [359]:
dados_raw.head(15)

,ID,MACRORREG_LPI,COD_UF_LPI,UF_LPI,COD_MUN_LPI,MUN_LPI,SEXO,IDADE,DT_IS,SE_IS,MES_IS,ANO_IS,MONITORAMENTO_IS,OBITO,DIA_IS
1,2,N,14,RR,140045.000,PACARAIMA,M,19,1995-02-19,8,2,1995,1994/1995,NÃO,19
2,3,NE,21,MA,210060.000,AMARANTE DO MARANHÃO,M,32,1995-04-01,13,4,1995,1994/1995,IGN,1
3,4,NE,21,MA,210060.000,AMARANTE DO MARANHÃO,M,33,1995-04-03,14,4,1995,1994/1995,SIM,3
4,5,N,15,PA,150270.000,CONCEIÇÃO DO ARAGUAIA,M,26,1995-04-12,15,4,1995,1994/1995,SIM,12
5,6,N,13,AM,130410.000,TAPAUÁ,M,29,1996-01-26,4,1,1996,1995/1996,SIM,26
6,7,N,13,AM,130356.000,RIO PRETO DA EVA,M,38,1996-01-27,4,1,1996,1995/1996,SIM,27
7,8,N,13,AM,130255.000,MANAQUIRI,M,46,1996-01-30,5,1,1996,1995/1996,SIM,30
8,9,N,13,AM,130250.000,MANACAPURU,M,20,1996-02-11,7,2,1996,1995/1996,SIM,11
10,11,N,13,AM,130110.000,CAREIRO,F,23,1996-03-13,11,3,1996,1995/1996,SIM,13
11,12,N,13,AM,130010.000,ANORI,M,14,1996-03-14,11,3,1996,1995/1996,SIM,14
12,13,N,13,AM,130255.000,MANAQUIRI,M,26,1996-03-16,11,3,1996,1995/1996,SIM,16
13,14,N,13,AM,130185.000,IRANDUBA,F,23,1996-03-17,12,3,1996,1995/1996,SIM,17
14,15,N,13,AM,130406.000,TABATINGA,M,21,1996-04-01,14,4,1996,1995/1996,NÃO,1
15,16,N,13,AM,130250.000,MANACAPURU,M,38,1996-06-30,27,6,1996,1995/1996,SIM,30
16,17,N,13,AM,130040.000,BARCELOS,M,20,1996-08-03,31,8,1996,1996/1997,NÃO,3

In [360]:
dados_raw.describe()

,ID,COD_UF_LPI,COD_MUN_LPI,IDADE,SE_IS,MES_IS,ANO_IS,DIA_IS
count,2734.000,2734.000,2734.000,2734.000,2734.000,2734.000,2734.000,2734.000
mean,1385.546,32.589,328316.085,42.663,9.321,2.591,2015.148,15.119
std,794.069,6.784,67862.508,16.591,11.724,2.735,5.939,8.373
min,2.000,11.000,110020.000,0.000,1.000,1.000,1995.000,1.000
25%,698.250,31.000,313885.000,31.000,3.000,1.000,2017.000,8.000
50%,1389.500,32.000,320190.000,43.000,5.000,2.000,2018.000,15.000
75%,2072.750,35.000,352007.500,55.000,10.000,3.000,2018.000,22.000
max,2758.000,53.000,530010.000,93.000,53.000,12.000,2021.000,31.000

Sames features / Variaveis repetidas

In [361]:
# States / Estados
dados_raw[['COD_UF_LPI','UF_LPI']]

      COD_UF_LPI UF_LPI
1             14     RR
2             21     MA
3             21     MA
4             15     PA
5             13     AM
...          ...    ...
2753          42     SC
2754          42     SC
2755          15     PA
2756          15     PA
2757          15     PA

[2734 rows x 2 columns]

In [362]:
# Cities / Cidades
dados_raw[['COD_MUN_LPI','MUN_LPI']]

      COD_MUN_LPI                MUN_LPI
1      140045.000              PACARAIMA
2      210060.000   AMARANTE DO MARANHÃO
3      210060.000   AMARANTE DO MARANHÃO
4      150270.000  CONCEIÇÃO DO ARAGUAIA
5      130410.000                 TAPAUÁ
...           ...                    ...
2753   420060.000           ÁGUAS MORNAS
2754   421780.000                   TAIÓ
2755   150030.000                   AFUÁ
2756   150030.000                   AFUÁ
2757   150520.000         OEIRAS DO PARÁ

[2734 rows x 2 columns]

In [363]:
dados_raw = dados_raw.drop(columns = dados_raw[['COD_UF_LPI','COD_MUN_LPI','DT_IS']], axis = 1)
dados_raw.head()

,ID,MACRORREG_LPI,UF_LPI,MUN_LPI,SEXO,IDADE,SE_IS,MES_IS,ANO_IS,MONITORAMENTO_IS,OBITO,DIA_IS
1,2,N,RR,PACARAIMA,M,19,8,2,1995,1994/1995,NÃO,19
2,3,NE,MA,AMARANTE DO MARANHÃO,M,32,13,4,1995,1994/1995,IGN,1
3,4,NE,MA,AMARANTE DO MARANHÃO,M,33,14,4,1995,1994/1995,SIM,3
4,5,N,PA,CONCEIÇÃO DO ARAGUAIA,M,26,15,4,1995,1994/1995,SIM,12
5,6,N,AM,TAPAUÁ,M,29,4,1,1996,1995/1996,SIM,26

Output dataset / Gerar arquivo

In [364]:
dados_raw.to_csv('yellow_fever_clean.csv')